basePath: /
definitions:
  handler.AggregatedResponse:
    properties:
      currency:
        description: Currency of the total cost (RUB for example)
        example: RUB
        type: string
      from_date:
        description: Start point of the aggregated data
        example: 01-2023
        type: string
      to_date:
        description: End point of the aggregated data (inclusive)
        example: 02-2023
        type: string
      total_cost:
        description: Total cost of the subscriptions with or without filters (service
          name or user id)
        example: 10000
        type: integer
    type: object
  handler.CreateSubscriptionDTO:
    properties:
      end_date:
        description: End date (formated as MM-YYYY) *Optional*
        type: string
      price:
        description: |-
          Price monthly in RUB
          required: true
        minimum: 0
        type: integer
      service_name:
        description: |-
          Name of the service (for example, "Spotify Premium")
          required: true
        type: string
      start_date:
        description: |-
          Start date (formated as MM-YYYY)
          required: true
        type: string
      user_id:
        description: |-
          User UUID
          required: true
        type: string
    required:
    - price
    - service_name
    - start_date
    - user_id
    type: object
  handler.SubscriptionResponse:
    properties:
      created_at:
        type: string
      end_date:
        type: string
      id:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: REST API for userdata aggregation of the subscriptions
  title: REST API Subscription service
  version: "1.0"
paths:
  /subscriptions:
    get:
      consumes:
      - application/json
      description: Retrieve all subscriptions with optional filters
      parameters:
      - description: Filter by user UUID
        in: query
        name: user_id
        type: string
      - description: Filter by service name
        in: query
        name: service_name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.SubscriptionResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List subscriptions
      tags:
      - subscriptions
    post:
      consumes:
      - application/json
      description: Create a new subscription
      parameters:
      - description: Subscription details
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handler.CreateSubscriptionDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.SubscriptionResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create subscription
      tags:
      - subscriptions
  /subscriptions/{id}:
    delete:
      description: Delete a subscription by ID
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete subscription
      tags:
      - subscriptions
    get:
      consumes:
      - application/json
      description: Retrieve a single subscription by its ID
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.SubscriptionResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get subscription by ID
      tags:
      - subscriptions
    put:
      consumes:
      - application/json
      description: Update existing subscription by ID
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: string
      - description: Updated subscription payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handler.CreateSubscriptionDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.SubscriptionResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update subscription
      tags:
      - subscriptions
  /subscriptions/aggregate:
    get:
      consumes:
      - application/json
      description: Calculate total subscription cost for a given period
      parameters:
      - description: Start of period (MM-YYYY or YYYY-MM)
        in: query
        name: from
        required: true
        type: string
      - description: End of period (MM-YYYY or YYYY-MM)
        in: query
        name: to
        required: true
        type: string
      - description: Filter by user UUID
        in: query
        name: user_id
        type: string
      - description: Filter by service name
        in: query
        name: service_name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.AggregatedResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Aggregate subscription costs
      tags:
      - subscriptions
swagger: "2.0"
