basePath: /
host: localhost:8000
info:
  contact: {}
  description: REST API сервис для агрегации данных об онлайн-подписках пользователей.
  title: REST API Subscription service
  version: "1.0"
paths: {}
swagger: "2.0"
